/*
 * Support for source maps in V8 stack traces
 * https://github.com/evanw/node-source-map-support
 */
(function(k,v,p){function g(e,a){if(!v[e]){if(!k[e]){var c="function"==typeof require&&require;if(!a&&c)return c(e,!0);if(D)return D(e,!0);throw Error("Cannot find module '"+e+"'");}c=v[e]={exports:{}};k[e][0].call(c.exports,function(a){var d=k[e][1][a];return g(d?d:a)},c,c.exports)}return v[e].exports}for(var D="function"==typeof require&&require,h=0;h<p.length;h++)g(p[h]);return g})({1:[function(k,v,p){k("./source-map-support").install()},{"./source-map-support":12}],2:[function(k,v,p){p.SourceMapGenerator=
k("./source-map/source-map-generator").SourceMapGenerator;p.SourceMapConsumer=k("./source-map/source-map-consumer").SourceMapConsumer;p.SourceNode=k("./source-map/source-node").SourceNode},{"./source-map/source-map-consumer":7,"./source-map/source-map-generator":8,"./source-map/source-node":9}],3:[function(k,v,p){if("function"!==typeof g)var g=k("amdefine")(v,k);g(function(g,h,e){function a(){this._array=[];this._set={}}var c=g("./util");a.fromArray=function(c,d){for(var f=new a,b=0,e=c.length;b<
e;b++)f.add(c[b],d);return f};a.prototype.add=function(a,d){var f=this.has(a),b=this._array.length;f&&!d||this._array.push(a);f||(this._set[c.toSetString(a)]=b)};a.prototype.has=function(a){return Object.prototype.hasOwnProperty.call(this._set,c.toSetString(a))};a.prototype.indexOf=function(a){if(this.has(a))return this._set[c.toSetString(a)];throw Error('"'+a+'" is not in the set.');};a.prototype.at=function(a){if(0<=a&&a<this._array.length)return this._array[a];throw Error("No element indexed by "+
a);};a.prototype.toArray=function(){return this._array.slice()};h.ArraySet=a})},{"./util":10,amdefine:11}],4:[function(k,v,p){if("function"!==typeof g)var g=k("amdefine")(v,k);g(function(g,h,e){var a=g("./base64");h.encode=function(c){var e="",d=0>c?(-c<<1)+1:(c<<1)+0;do c=d&31,d>>>=5,0<d&&(c|=32),e+=a.encode(c);while(0<d);return e};h.decode=function(c){var e=0,d=c.length,f=0,b=0,q,w;do{if(e>=d)throw Error("Expected more digits in base 64 VLQ value.");w=a.decode(c.charAt(e++));q=!!(w&32);w&=31;f+=
w<<b;b+=5}while(q);d=f>>1;return{value:1===(f&1)?-d:d,rest:c.slice(e)}}})},{"./base64":5,amdefine:11}],5:[function(k,v,p){if("function"!==typeof g)var g=k("amdefine")(v,k);g(function(g,h,e){var a={},c={};"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".split("").forEach(function(e,d){a[e]=d;c[d]=e});h.encode=function(a){if(a in c)return c[a];throw new TypeError("Must be between 0 and 63: "+a);};h.decode=function(c){if(c in a)return a[c];throw new TypeError("Not a valid base 64 digit: "+
c);}})},{amdefine:11}],6:[function(k,v,p){if("function"!==typeof g)var g=k("amdefine")(v,k);g(function(g,h,e){function a(c,e,d,f,b){var q=Math.floor((e-c)/2)+c,w=b(d,f[q]);return 0===w?f[q]:0<w?1<e-q?a(q,e,d,f,b):f[q]:1<q-c?a(c,q,d,f,b):0>c?null:f[c]}h.search=function(c,e,d){return 0<e.length?a(-1,e.length,c,e,d):null}})},{amdefine:11}],7:[function(k,v,p){if("function"!==typeof g)var g=k("amdefine")(v,k);g(function(g,h,e){function a(b){var a=b;"string"===typeof b&&(a=JSON.parse(b.replace(/^\)\]\}'/,
"")));b=c.getArg(a,"version");var f=c.getArg(a,"sources"),e=c.getArg(a,"names"),m=c.getArg(a,"sourceRoot",null),g=c.getArg(a,"sourcesContent",null),r=c.getArg(a,"mappings"),a=c.getArg(a,"file",null);if(b!==this._version)throw Error("Unsupported version: "+b);this._names=d.fromArray(e,!0);this._sources=d.fromArray(f,!0);this.sourceRoot=m;this.sourcesContent=g;this.file=a;this._generatedMappings=[];this._originalMappings=[];this._parseMappings(r,m)}var c=g("./util"),m=g("./binary-search"),d=g("./array-set").ArraySet,
f=g("./base64-vlq");a.prototype._version=3;Object.defineProperty(a.prototype,"sources",{get:function(){return this._sources.toArray().map(function(b){return this.sourceRoot?c.join(this.sourceRoot,b):b},this)}});a.prototype._parseMappings=function(b,a){for(var d=1,c=0,e=0,m=0,r=0,s=0,u=/^[,;]/,n=b,g;0<n.length;)if(";"===n.charAt(0))d++,n=n.slice(1),c=0;else if(","===n.charAt(0))n=n.slice(1);else{g={};g.generatedLine=d;n=f.decode(n);g.generatedColumn=c+n.value;c=g.generatedColumn;n=n.rest;if(0<n.length&&
!u.test(n.charAt(0))){n=f.decode(n);g.source=this._sources.at(r+n.value);r+=n.value;n=n.rest;if(0===n.length||u.test(n.charAt(0)))throw Error("Found a source, but no line and column");n=f.decode(n);g.originalLine=e+n.value;e=g.originalLine;g.originalLine+=1;n=n.rest;if(0===n.length||u.test(n.charAt(0)))throw Error("Found a source and line, but no column");n=f.decode(n);g.originalColumn=m+n.value;m=g.originalColumn;n=n.rest;0<n.length&&!u.test(n.charAt(0))&&(n=f.decode(n),g.name=this._names.at(s+n.value),
s+=n.value,n=n.rest)}this._generatedMappings.push(g);"number"===typeof g.originalLine&&this._originalMappings.push(g)}this._originalMappings.sort(this._compareOriginalPositions)};a.prototype._compareOriginalPositions=function(b,a){if(b.source>a.source)return 1;if(b.source<a.source)return-1;var d=b.originalLine-a.originalLine;return 0===d?b.originalColumn-a.originalColumn:d};a.prototype._compareGeneratedPositions=function(b,a){var d=b.generatedLine-a.generatedLine;return 0===d?b.generatedColumn-a.generatedColumn:
d};a.prototype._findMapping=function(b,a,d,c,f){if(0>=b[d])throw new TypeError("Line must be greater than or equal to 1, got "+b[d]);if(0>b[c])throw new TypeError("Column must be greater than or equal to 0, got "+b[c]);return m.search(b,a,f)};a.prototype.originalPositionFor=function(b){b={generatedLine:c.getArg(b,"line"),generatedColumn:c.getArg(b,"column")};if(b=this._findMapping(b,this._generatedMappings,"generatedLine","generatedColumn",this._compareGeneratedPositions)){var a=c.getArg(b,"source",
null);a&&this.sourceRoot&&(a=c.join(this.sourceRoot,a));return{source:a,line:c.getArg(b,"originalLine",null),column:c.getArg(b,"originalColumn",null),name:c.getArg(b,"name",null)}}return{source:null,line:null,column:null,name:null}};a.prototype.sourceContentFor=function(b){if(!this.sourcesContent)return null;this.sourceRoot&&(b=c.relative(this.sourceRoot,b));if(this._sources.has(b))return this.sourcesContent[this._sources.indexOf(b)];var a;if(this.sourceRoot&&(a=c.urlParse(this.sourceRoot))){var d=
b.replace(/^file:\/\//,"");if("file"==a.scheme&&this._sources.has(d))return this.sourcesContent[this._sources.indexOf(d)];if((!a.path||"/"==a.path)&&this._sources.has("/"+b))return this.sourcesContent[this._sources.indexOf("/"+b)]}throw Error('"'+b+'" is not in the SourceMap.');};a.prototype.generatedPositionFor=function(b){b={source:c.getArg(b,"source"),originalLine:c.getArg(b,"line"),originalColumn:c.getArg(b,"column")};this.sourceRoot&&(b.source=c.relative(this.sourceRoot,b.source));return(b=this._findMapping(b,
this._originalMappings,"originalLine","originalColumn",this._compareOriginalPositions))?{line:c.getArg(b,"generatedLine",null),column:c.getArg(b,"generatedColumn",null)}:{line:null,column:null}};a.GENERATED_ORDER=1;a.ORIGINAL_ORDER=2;a.prototype.eachMapping=function(b,d,f){d=d||null;switch(f||a.GENERATED_ORDER){case a.GENERATED_ORDER:f=this._generatedMappings;break;case a.ORIGINAL_ORDER:f=this._originalMappings;break;default:throw Error("Unknown order of iteration.");}var e=this.sourceRoot;f.map(function(b){var a=
b.source;a&&e&&(a=c.join(e,a));return{source:a,generatedLine:b.generatedLine,generatedColumn:b.generatedColumn,originalLine:b.originalLine,originalColumn:b.originalColumn,name:b.name}}).forEach(b,d)};h.SourceMapConsumer=a})},{"./array-set":3,"./base64-vlq":4,"./binary-search":6,"./util":10,amdefine:11}],8:[function(k,v,p){if("function"!==typeof g)var g=k("amdefine")(v,k);g(function(g,h,e){function a(a){this._file=b.getArg(a,"file");this._sourceRoot=b.getArg(a,"sourceRoot",null);this._sources=new q;
this._names=new q;this._mappings=[];this._sourcesContents=null}function c(b,a){var d=(b&&b.line)-(a&&a.line);return d?d:(b&&b.column)-(a&&a.column)}function m(b,a){b=b||"";a=a||"";return(b>a)-(b<a)}function d(b,a){return c(b.generated,a.generated)||c(b.original,a.original)||m(b.source,a.source)||m(b.name,a.name)}var f=g("./base64-vlq"),b=g("./util"),q=g("./array-set").ArraySet;a.prototype._version=3;a.fromSourceMap=function(d){var c=d.sourceRoot,f=new a({file:d.file,sourceRoot:c});d.eachMapping(function(a){var d=
{generated:{line:a.generatedLine,column:a.generatedColumn}};a.source&&(d.source=a.source,c&&(d.source=b.relative(c,d.source)),d.original={line:a.originalLine,column:a.originalColumn},a.name&&(d.name=a.name));f.addMapping(d)});d.sources.forEach(function(b){var a=d.sourceContentFor(b);a&&f.setSourceContent(b,a)});return f};a.prototype.addMapping=function(a){var d=b.getArg(a,"generated"),c=b.getArg(a,"original",null),f=b.getArg(a,"source",null);a=b.getArg(a,"name",null);this._validateMapping(d,c,f,a);
f&&!this._sources.has(f)&&this._sources.add(f);a&&!this._names.has(a)&&this._names.add(a);this._mappings.push({generated:d,original:c,source:f,name:a})};a.prototype.setSourceContent=function(a,d){var c=a;this._sourceRoot&&(c=b.relative(this._sourceRoot,c));null!==d?(this._sourcesContents||(this._sourcesContents={}),this._sourcesContents[b.toSetString(c)]=d):(delete this._sourcesContents[b.toSetString(c)],0===Object.keys(this._sourcesContents).length&&(this._sourcesContents=null))};a.prototype.applySourceMap=
function(a,d){d||(d=a.file);var c=this._sourceRoot;c&&(d=b.relative(c,d));var f=new q,e=new q;this._mappings.forEach(function(s){if(s.source===d&&s.original){var u=a.originalPositionFor({line:s.original.line,column:s.original.column});null!==u.source&&(s.source=c?b.relative(c,u.source):u.source,s.original.line=u.line,s.original.column=u.column,null!==u.name&&null!==s.name&&(s.name=u.name))}(u=s.source)&&!f.has(u)&&f.add(u);(s=s.name)&&!e.has(s)&&e.add(s)},this);this._sources=f;this._names=e;a.sources.forEach(function(d){var f=
a.sourceContentFor(d);f&&(c&&(d=b.relative(c,d)),this.setSourceContent(d,f))},this)};a.prototype._validateMapping=function(b,a,d,c){if(!(b&&"line"in b&&"column"in b&&0<b.line&&0<=b.column&&!a&&!d&&!c||b&&"line"in b&&"column"in b&&a&&"line"in a&&"column"in a&&0<b.line&&0<=b.column&&0<a.line&&0<=a.column&&d))throw Error("Invalid mapping.");};a.prototype._serializeMappings=function(){var b=0,a=1,c=0,e=0,m=0,s=0,u="",n;this._mappings.sort(d);for(var q=0,g=this._mappings.length;q<g;q++){n=this._mappings[q];
if(n.generated.line!==a)for(b=0;n.generated.line!==a;)u+=";",a++;else if(0<q){if(!d(n,this._mappings[q-1]))continue;u+=","}u+=f.encode(n.generated.column-b);b=n.generated.column;n.source&&n.original&&(u+=f.encode(this._sources.indexOf(n.source)-s),s=this._sources.indexOf(n.source),u+=f.encode(n.original.line-1-e),e=n.original.line-1,u+=f.encode(n.original.column-c),c=n.original.column,n.name&&(u+=f.encode(this._names.indexOf(n.name)-m),m=this._names.indexOf(n.name)))}return u};a.prototype.toJSON=
function(){var a={version:this._version,file:this._file,sources:this._sources.toArray(),names:this._names.toArray(),mappings:this._serializeMappings()};this._sourceRoot&&(a.sourceRoot=this._sourceRoot);this._sourcesContents&&(a.sourcesContent=a.sources.map(function(d){a.sourceRoot&&(d=b.relative(a.sourceRoot,d));return Object.prototype.hasOwnProperty.call(this._sourcesContents,b.toSetString(d))?this._sourcesContents[b.toSetString(d)]:null},this));return a};a.prototype.toString=function(){return JSON.stringify(this)};
h.SourceMapGenerator=a})},{"./array-set":3,"./base64-vlq":4,"./util":10,amdefine:11}],9:[function(k,v,p){if("function"!==typeof g)var g=k("amdefine")(v,k);g(function(g,h,e){function a(a,c,b,e,m){this.children=[];this.sourceContents={};this.line=void 0===a?null:a;this.column=void 0===c?null:c;this.source=void 0===b?null:b;this.name=void 0===m?null:m;null!=e&&this.add(e)}var c=g("./source-map-generator").SourceMapGenerator,m=g("./util");a.fromStringWithSourceMap=function(d,c){function b(b,d){null===
b||void 0===b.source?e.add(d):e.add(new a(b.originalLine,b.originalColumn,b.source,d,b.name))}var e=new a,m=d.split("\n"),g=1,h=0,k=null;c.eachMapping(function(a){if(null===k){for(;g<a.generatedLine;)e.add(m.shift()+"\n"),g++;if(h<a.generatedColumn){var d=m[0];e.add(d.substr(0,a.generatedColumn));m[0]=d.substr(a.generatedColumn);h=a.generatedColumn}}else{if(g<a.generatedLine){var c="";do c+=m.shift()+"\n",g++,h=0;while(g<a.generatedLine);h<a.generatedColumn&&(d=m[0],c+=d.substr(0,a.generatedColumn),
m[0]=d.substr(a.generatedColumn),h=a.generatedColumn)}else d=m[0],c=d.substr(0,a.generatedColumn-h),m[0]=d.substr(a.generatedColumn-h),h=a.generatedColumn;b(k,c)}k=a},this);b(k,m.join("\n"));c.sources.forEach(function(b){var a=c.sourceContentFor(b);a&&e.setSourceContent(b,a)});return e};a.prototype.add=function(d){if(Array.isArray(d))d.forEach(function(a){this.add(a)},this);else if(d instanceof a||"string"===typeof d)d&&this.children.push(d);else throw new TypeError("Expected a SourceNode, string, or an array of SourceNodes and strings. Got "+
d);return this};a.prototype.prepend=function(d){if(Array.isArray(d))for(var c=d.length-1;0<=c;c--)this.prepend(d[c]);else if(d instanceof a||"string"===typeof d)this.children.unshift(d);else throw new TypeError("Expected a SourceNode, string, or an array of SourceNodes and strings. Got "+d);return this};a.prototype.walk=function(d){this.children.forEach(function(c){c instanceof a?c.walk(d):""!==c&&d(c,{source:this.source,line:this.line,column:this.column,name:this.name})},this)};a.prototype.join=
function(a){var c,b,e=this.children.length;if(0<e){c=[];for(b=0;b<e-1;b++)c.push(this.children[b]),c.push(a);c.push(this.children[b]);this.children=c}return this};a.prototype.replaceRight=function(d,c){var b=this.children[this.children.length-1];b instanceof a?b.replaceRight(d,c):"string"===typeof b?this.children[this.children.length-1]=b.replace(d,c):this.children.push("".replace(d,c));return this};a.prototype.setSourceContent=function(a,c){this.sourceContents[m.toSetString(a)]=c};a.prototype.walkSourceContents=
function(d){this.children.forEach(function(c){c instanceof a&&c.walkSourceContents(d)},this);Object.keys(this.sourceContents).forEach(function(a){d(m.fromSetString(a),this.sourceContents[a])},this)};a.prototype.toString=function(){var a="";this.walk(function(c){a+=c});return a};a.prototype.toStringWithSourceMap=function(a){var e="",b=1,m=0,g=new c(a),h=!1,k=null,y=null,r=null,s=null;this.walk(function(a,d){e+=a;null!==d.source&&null!==d.line&&null!==d.column?(k===d.source&&y===d.line&&r===d.column&&
s===d.name||g.addMapping({source:d.source,original:{line:d.line,column:d.column},generated:{line:b,column:m},name:d.name}),k=d.source,y=d.line,r=d.column,s=d.name,h=!0):h&&(g.addMapping({generated:{line:b,column:m}}),k=null,h=!1);a.split("").forEach(function(a){"\n"===a?(b++,m=0):m++})});this.walkSourceContents(function(a,b){g.setSourceContent(a,b)});return{code:e,map:g}};h.SourceNode=a})},{"./source-map-generator":8,"./util":10,amdefine:11}],10:[function(k,v,p){if("function"!==typeof g)var g=k("amdefine")(v,
k);g(function(g,h,e){function a(a){return(a=a.match(m))?{scheme:a[1],auth:a[3],host:a[4],port:a[6],path:a[7]}:null}function c(a){var c=a.scheme+"://";a.auth&&(c+=a.auth+"@");a.host&&(c+=a.host);a.port&&(c+=":"+a.port);a.path&&(c+=a.path);return c}h.getArg=function(a,c,b){if(c in a)return a[c];if(3===arguments.length)return b;throw Error('"'+c+'" is a required argument.');};var m=/([\w+\-.]+):\/\/((\w+:\w+)@)?([\w.]+)?(:(\d+))?(\S+)?/;h.urlParse=a;h.urlGenerate=c;h.join=function(d,e){var b;return e.match(m)?
e:"/"===e.charAt(0)&&(b=a(d))?(b.path=e,c(b)):d.replace(/\/$/,"")+"/"+e};h.toSetString=function(a){return"$"+a};h.fromSetString=function(a){return a.substr(1)};h.relative=function(c,e){c=c.replace(/\/$/,"");var b=a(c);return"/"==e.charAt(0)&&b&&"/"==b.path?e.slice(1):0===e.indexOf(c+"/")?e.substr(c.length+1):e}})},{amdefine:11}],11:[function(k,v,p){(function(g,D){v.exports=function(h,e){function a(a,b){var c;if(a&&"."===a.charAt(0)&&b){c=b.split("/");c=c.slice(0,c.length-1);var d=c=c.concat(a.split("/")),
e,f;for(e=0;d[e];e+=1)if(f=d[e],"."===f)d.splice(e,1),e-=1;else if(".."===f)if(1!==e||".."!==d[2]&&".."!==d[0])0<e&&(d.splice(e-1,2),e-=2);else break;a=c.join("/")}return a}function c(b){return function(c){return a(c,b)}}function m(a){function b(c){q[a]=c}b.fromText=function(a,b){throw Error("amdefine does not implement load.fromText");};return b}function d(a,b,c){var d,f,m;if(a)f=q[a]={},m={id:a,uri:D,exports:f},d=t(e,f,m,a);else{if(w)throw Error("amdefine with no module ID cannot be called more than once per file.");
w=!0;f=h.exports;m=h;d=t(e,f,m,h.id)}b&&(b=b.map(function(a){return d(a)}));b="function"===typeof c?c.apply(m.exports,b):c;void 0!==b&&(m.exports=b,a&&(q[a]=m.exports))}function f(a,c,e){Array.isArray(a)?(e=c,c=a,a=void 0):"string"!==typeof a&&(e=a,a=c=void 0);c&&!Array.isArray(c)&&(e=c,c=void 0);c||(c=["require","exports","module"]);a?b[a]=[a,c,e]:d(a,c,e)}var b={},q={},w=!1,z=k("path"),t,y;t=function(b,c,d,e){function f(a,m){if("string"===typeof a)return y(b,c,d,a,e);a=a.map(function(a){return y(b,
c,d,a,e)});g.nextTick(function(){m.apply(null,a)})}f.toUrl=function(b){return 0===b.indexOf(".")?a(b,z.dirname(d.filename)):b};return f};e=e||function(){return h.require.apply(h,arguments)};y=function(e,f,u,n,g){var h=n.indexOf("!"),w=n;if(-1===h){n=a(n,g);if("require"===n)return t(e,f,u,g);if("exports"===n)return f;if("module"===n)return u;if(q.hasOwnProperty(n))return q[n];if(b[n])return d.apply(null,b[n]),q[n];if(e)return e(w);throw Error("No module with ID: "+n);}w=n.substring(0,h);n=n.substring(h+
1,n.length);h=y(e,f,u,w,g);n=h.normalize?h.normalize(n,c(g)):a(n,g);q[n]||h.load(n,t(e,f,u,g),m(n),{});return q[n]};f.require=function(a){if(q[a])return q[a];if(b[a])return d.apply(null,b[a]),q[a]};f.amd={};return f}})(k("__browserify_process"),"/node_modules/source-map/node_modules/amdefine/amdefine.js")},{__browserify_process:16,path:14}],12:[function(k,v,p){(function(g,D){function h(a){if(a in z)return z[a];try{if("undefined"!==typeof window){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);
var c=4===b.readyState?b.responseText:null}else c=q.readFileSync(a,"utf8")}catch(d){c=null}return z[a]=c}function e(a,c){var d=/^\w+:\/\/[^\/]*/.exec(a),d=d?d[0]:"";return d+b.resolve(a.slice(d.length),c)}function a(b){var c=/^eval at ([^(]+) \((.+):(\d+):(\d+)\)$/.exec(b);return c?(b=r({source:c[2],line:c[3],column:c[4]}),"eval at "+c[1]+" ("+b.source+":"+b.line+":"+b.column+")"):(c=/^eval at ([^(]+) \((.+)\)$/.exec(b))?"eval at "+c[1]+" ("+a(c[2])+")":b}function c(b){var c=b.getFileName()||b.getScriptNameOrSourceURL();
if(c){var d=r({source:c,line:b.getLineNumber(),column:b.getColumnNumber()});return{__proto__:b,getFileName:function(){return d.source},getLineNumber:function(){return d.line},getColumnNumber:function(){return d.column},getScriptNameOrSourceURL:function(){return d.source}}}var e=b.isEval()&&b.getEvalOrigin();return e?(e=a(e),{__proto__:b,getEvalOrigin:function(){return e}}):b}function m(a,b){w&&(z={},t={});return a+b.map(function(a){return"\n    at "+c(a)}).join("")}function d(a){a&&a.stack||(console.log("Uncaught exception:",
a),g.exit());var b=/\n    at [^(]+ \((.*):(\d+):(\d+)\)/.exec(a.stack);if(b&&(b=r({source:b[1],line:b[2],column:b[3]}),q.existsSync(b.source))){var c=q.readFileSync(b.source,"utf8").split(/(?:\r\n|\r|\n)/)[b.line-1];c&&(console.log("\n"+b.source+":"+b.line),console.log(c),console.log(Array(+b.column).join(" ")+"^"))}console.log(a.stack);g.exit()}var f=k("source-map").SourceMapConsumer,b=k("path"),q=k("fs"),w=!1,z={},t={},y=function(a){var c=h(a),c=/\/\/[#@]\s*sourceMappingURL=(.*)\s*$/m.exec(c);if(!c)return null;
c=c[1];"data:application/json;base64,"==c.slice(0,29).toLowerCase()?a=(new D(c.slice(29),"base64")).toString():(a=b.dirname(a),c=e(a,c),a=h(c,"utf8"));return a?{url:c,map:a}:null},r=p.mapSourcePosition=function(a){var c=t[a.source];if(!c){var d=y(a.source);d&&(c=t[a.source]={url:d.url,map:new f(d.map)})}return c&&(d=c.map.originalPositionFor(a),null!==d.source)?(c.url&&(d.source=e(b.dirname(c.url),d.source)),d):a};p.install=function(a){Error.prepareStackTrace=m;a=a||{};var b="handleUncaughtExceptions"in
a?a.handleUncaughtExceptions:!0;w="emptyCacheBetweenOperations"in a?a.emptyCacheBetweenOperations:!1;a.retrieveSourceMap&&(y=a.retrieveSourceMap);if(b&&"undefined"===typeof window)g.on("uncaughtException",d)}})(k("__browserify_process"),k("__browserify_Buffer").Buffer)},{__browserify_Buffer:15,__browserify_process:16,fs:13,path:14,"source-map":2}],13:[function(k,v,p){},{}],14:[function(k,v,p){(function(g){function k(a,c){for(var e=[],d=0;d<a.length;d++)c(a[d],d,a)&&e.push(a[d]);return e}function h(a,
c){for(var e=0,d=a.length;0<=d;d--){var f=a[d];"."==f?a.splice(d,1):".."===f?(a.splice(d,1),e++):e&&(a.splice(d,1),e--)}if(c)for(;e--;e)a.unshift("..");return a}var e=/^(.+\/(?!$)|\/)?((?:.+?)?(\.[^.]*)?)$/;p.resolve=function(){for(var a="",c=!1,e=arguments.length;-1<=e&&!c;e--){var d=0<=e?arguments[e]:g.cwd();"string"===typeof d&&d&&(a=d+"/"+a,c="/"===d.charAt(0))}a=h(k(a.split("/"),function(a){return!!a}),!c).join("/");return(c?"/":"")+a||"."};p.normalize=function(a){var c="/"===a.charAt(0),e="/"===
a.slice(-1);(a=h(k(a.split("/"),function(a){return!!a}),!c).join("/"))||c||(a=".");a&&e&&(a+="/");return(c?"/":"")+a};p.join=function(){var a=Array.prototype.slice.call(arguments,0);return p.normalize(k(a,function(a,e){return a&&"string"===typeof a}).join("/"))};p.dirname=function(a){return(a=e.exec(a)[1]||"")?1===a.length?a:a.substring(0,a.length-1):"."};p.basename=function(a,c){var m=e.exec(a)[2]||"";c&&m.substr(-1*c.length)===c&&(m=m.substr(0,m.length-c.length));return m};p.extname=function(a){return e.exec(a)[3]||
""};p.relative=function(a,c){function e(a){for(var b=0;b<a.length&&""===a[b];b++);for(var c=a.length-1;0<=c&&""===a[c];c--);return b>c?[]:a.slice(b,c-b+1)}a=p.resolve(a).substr(1);c=p.resolve(c).substr(1);for(var d=e(a.split("/")),f=e(c.split("/")),b=Math.min(d.length,f.length),g=b,h=0;h<b;h++)if(d[h]!==f[h]){g=h;break}b=[];for(h=g;h<d.length;h++)b.push("..");b=b.concat(f.slice(g));return b.join("/")}})(k("__browserify_process"))},{__browserify_process:16}],15:[function(k,v,p){k=function(g,k,h,e){function a(c){if(!h[c]){if(!k[c]){if(g)return g(c);
throw Error("Cannot find module '"+c+"'");}var d=h[c]={exports:{}};k[c][0](function(d){var b=k[c][1][d];return a(b?b:d)},d,d.exports)}return h[c].exports}for(var c=0;c<e.length;c++)a(e[c]);return a}("undefined"!==typeof k&&k,{1:[function(g,k,h){function e(a){if(Object.keys)return Object.keys(a);var b=[],c;for(c in a)Object.prototype.hasOwnProperty.call(a,c)&&b.push(c);return b}function a(a,b){return void 0===b?""+b:"number"===typeof b&&(isNaN(b)||!isFinite(b))||"function"===typeof b||b instanceof
RegExp?b.toString():b}function c(a,b){return"string"==typeof a?a.length<b?a:a.slice(0,b):a}function m(a,b,c,d,e){throw new r.AssertionError({message:c,actual:a,expected:b,operator:d,stackStartFunction:e});}function d(a,b){a||m(a,!0,b,"==",r.ok)}function f(a,b){if(a===b)return!0;if(t.isBuffer(a)&&t.isBuffer(b)){if(a.length!=b.length)return!1;for(var c=0;c<a.length;c++)if(a[c]!==b[c])return!1;return!0}return a instanceof Date&&b instanceof Date?a.getTime()===b.getTime():"object"!=typeof a&&"object"!=
typeof b?a==b:q(a,b)}function b(a){return"[object Arguments]"==Object.prototype.toString.call(a)}function q(a,c){if(null===a||void 0===a||(null===c||void 0===c)||a.prototype!==c.prototype)return!1;if(b(a)){if(!b(c))return!1;a=y.call(a);c=y.call(c);return f(a,c)}try{var d=e(a),m=e(c),g}catch(h){return!1}if(d.length!=m.length)return!1;d.sort();m.sort();for(g=d.length-1;0<=g;g--)if(d[g]!=m[g])return!1;for(g=d.length-1;0<=g;g--)if(m=d[g],!f(a[m],c[m]))return!1;return!0}function w(a,b){return a&&b?b instanceof
RegExp?b.test(a):a instanceof b||!0===b.call({},a)?!0:!1:!1}function z(a,b,c,d){var e;"string"===typeof c&&(d=c,c=null);try{b()}catch(f){e=f}d=(c&&c.name?" ("+c.name+").":".")+(d?" "+d:".");a&&!e&&m("Missing expected exception"+d);!a&&w(e,c)&&m("Got unwanted exception"+d);if(a&&e&&c&&!w(e,c)||!a&&e)throw e;}h=g("util");var t=g("buffer").Buffer,y=Array.prototype.slice,r=k.exports=d;r.AssertionError=function(a){this.name="AssertionError";this.message=a.message;this.actual=a.actual;this.expected=a.expected;
this.operator=a.operator;a=a.stackStartFunction||m;Error.captureStackTrace&&Error.captureStackTrace(this,a)};h.inherits(r.AssertionError,Error);r.AssertionError.prototype.toString=function(){return this.message?[this.name+":",this.message].join(" "):[this.name+":",c(JSON.stringify(this.actual,a),128),this.operator,c(JSON.stringify(this.expected,a),128)].join(" ")};r.AssertionError.__proto__=Error.prototype;r.fail=m;r.ok=d;r.equal=function(a,b,c){a!=b&&m(a,b,c,"==",r.equal)};r.notEqual=function(a,
b,c){a==b&&m(a,b,c,"!=",r.notEqual)};r.deepEqual=function(a,b,c){f(a,b)||m(a,b,c,"deepEqual",r.deepEqual)};r.notDeepEqual=function(a,b,c){f(a,b)&&m(a,b,c,"notDeepEqual",r.notDeepEqual)};r.strictEqual=function(a,b,c){a!==b&&m(a,b,c,"===",r.strictEqual)};r.notStrictEqual=function(a,b,c){a===b&&m(a,b,c,"!==",r.notStrictEqual)};r["throws"]=function(a,b,c){z.apply(this,[!0].concat(y.call(arguments)))};r.doesNotThrow=function(a,b,c){z.apply(this,[!1].concat(y.call(arguments)))};r.ifError=function(a){if(a)throw a;
}},{util:2,buffer:3}],2:[function(g,k,h){function e(a){return a instanceof Array||Array.isArray(a)||a&&a!==Object.prototype&&e(a.__proto__)}function a(a){return a instanceof RegExp||"object"===typeof a&&"[object RegExp]"===Object.prototype.toString.call(a)}function c(a){if(a instanceof Date)return!0;if("object"!==typeof a)return!1;var b=Date.prototype&&d(Date.prototype);a=a.__proto__&&d(a.__proto__);return JSON.stringify(a)===JSON.stringify(b)}g("events");h.isArray=e;h.isDate=function(a){return"[object Date]"===
Object.prototype.toString.call(a)};h.isRegExp=function(a){return"[object RegExp]"===Object.prototype.toString.call(a)};h.print=function(){};h.puts=function(){};h.debug=function(){};h.inspect=function(b,f,g,k){function y(b,g){if(b&&"function"===typeof b.inspect&&b!==h&&(!b.constructor||b.constructor.prototype!==b))return b.inspect(g);switch(typeof b){case "undefined":return s("undefined","undefined");case "string":var q="'"+JSON.stringify(b).replace(/^"|"$/g,"").replace(/'/g,"\\'").replace(/\\"/g,
'"')+"'";return s(q,"string");case "number":return s(""+b,"number");case "boolean":return s(""+b,"boolean")}if(null===b)return s("null","null");var k=m(b),z=f?d(b):k;if("function"===typeof b&&0===z.length)return a(b)?s(""+b,"regexp"):s("[Function"+(b.name?": "+b.name:"")+"]","special");if(c(b)&&0===z.length)return s(b.toUTCString(),"date");var t,p;e(b)?(p="Array",q=["[","]"]):(p="Object",q=["{","}"]);"function"===typeof b?(t=b.name?": "+b.name:"",t=a(b)?" "+b:" [Function"+t+"]"):t="";c(b)&&(t=" "+
b.toUTCString());if(0===z.length)return q[0]+t+q[1];if(0>g)return a(b)?s(""+b,"regexp"):s("[Object]","special");r.push(b);z=z.map(function(a){var c,B;b.__lookupGetter__&&(b.__lookupGetter__(a)?B=b.__lookupSetter__(a)?s("[Getter/Setter]","special"):s("[Getter]","special"):b.__lookupSetter__(a)&&(B=s("[Setter]","special")));0>k.indexOf(a)&&(c="["+a+"]");B||(0>r.indexOf(b[a])?(B=null===g?y(b[a]):y(b[a],g-1),-1<B.indexOf("\n")&&(B=e(b)?B.split("\n").map(function(B){return"  "+B}).join("\n").substr(2):
"\n"+B.split("\n").map(function(B){return"   "+B}).join("\n"))):B=s("[Circular]","special"));if("undefined"===typeof c){if("Array"===p&&a.match(/^\d+$/))return B;c=JSON.stringify(""+a);c.match(/^"([a-zA-Z_][a-zA-Z_0-9]*)"$/)?(c=c.substr(1,c.length-2),c=s(c,"name")):(c=c.replace(/'/g,"\\'").replace(/\\"/g,'"').replace(/(^"|"$)/g,"'"),c=s(c,"string"))}return c+": "+B});r.pop();var D=0;return z=50<z.reduce(function(a,b){D++;0<=b.indexOf("\n")&&D++;return a+b.length+1},0)?q[0]+(""===t?"":t+"\n ")+" "+
z.join(",\n  ")+" "+q[1]:q[0]+t+" "+z.join(", ")+" "+q[1]}var r=[],s=function(a,b){var c={bold:[1,22],italic:[3,23],underline:[4,24],inverse:[7,27],white:[37,39],grey:[90,39],black:[30,39],blue:[34,39],cyan:[36,39],green:[32,39],magenta:[35,39],red:[31,39],yellow:[33,39]},d={special:"cyan",number:"blue","boolean":"yellow",undefined:"grey","null":"bold",string:"green",date:"magenta",regexp:"red"}[b];return d?"\u001b["+c[d][0]+"m"+a+"\u001b["+c[d][1]+"m":a};k||(s=function(a,b){return a});return y(b,
"undefined"===typeof g?2:g)};h.log=function(a){};h.pump=null;var m=Object.keys||function(a){var b=[],c;for(c in a)b.push(c);return b},d=Object.getOwnPropertyNames||function(a){var b=[],c;for(c in a)Object.hasOwnProperty.call(a,c)&&b.push(c);return b},f=Object.create||function(a,b){var c;if(null===a)c={__proto__:null};else{if("object"!==typeof a)throw new TypeError("typeof prototype["+typeof a+"] != 'object'");c=function(){};c.prototype=a;c=new c;c.__proto__=a}"undefined"!==typeof b&&Object.defineProperties&&
Object.defineProperties(c,b);return c};h.inherits=function(a,b){a.super_=b;a.prototype=f(b.prototype,{constructor:{value:a,enumerable:!1,writable:!0,configurable:!0}})};var b=/%[sdj%]/g;h.format=function(a){if("string"!==typeof a){for(var c=[],d=0;d<arguments.length;d++)c.push(h.inspect(arguments[d]));return c.join(" ")}for(var d=1,e=arguments,f=e.length,c=String(a).replace(b,function(a){if("%%"===a)return"%";if(d>=f)return a;switch(a){case "%s":return String(e[d++]);case "%d":return Number(e[d++]);
case "%j":return JSON.stringify(e[d++]);default:return a}}),m=e[d];d<f;m=e[++d])c=null===m||"object"!==typeof m?c+(" "+m):c+(" "+h.inspect(m));return c}},{events:4}],5:[function(g,k,h){h.readIEEE754=function(e,a,c,m,d){var f;f=8*d-m-1;var b=(1<<f)-1,g=b>>1,h=-7;d=c?0:d-1;var k=c?1:-1,t=e[a+d];d+=k;c=t&(1<<-h)-1;t>>=-h;for(h+=f;0<h;c=256*c+e[a+d],d+=k,h-=8);f=c&(1<<-h)-1;c>>=-h;for(h+=m;0<h;f=256*f+e[a+d],d+=k,h-=8);if(0===c)c=1-g;else{if(c===b)return f?NaN:Infinity*(t?-1:1);f+=Math.pow(2,m);c-=g}return(t?
-1:1)*f*Math.pow(2,c-m)};h.writeIEEE754=function(e,a,c,m,d,f){var b,g=8*f-d-1,h=(1<<g)-1,k=h>>1,t=23===d?Math.pow(2,-24)-Math.pow(2,-77):0;f=m?f-1:0;var p=m?-1:1,r=0>a||0===a&&0>1/a?1:0;a=Math.abs(a);isNaN(a)||Infinity===a?(a=isNaN(a)?1:0,m=h):(m=Math.floor(Math.log(a)/Math.LN2),1>a*(b=Math.pow(2,-m))&&(m--,b*=2),a=1<=m+k?a+t/b:a+t*Math.pow(2,1-k),2<=a*b&&(m++,b/=2),m+k>=h?(a=0,m=h):1<=m+k?(a=(a*b-1)*Math.pow(2,d),m+=k):(a=a*Math.pow(2,k-1)*Math.pow(2,d),m=0));for(;8<=d;e[c+f]=a&255,f+=p,a/=256,d-=
8);m=m<<d|a;for(g+=d;0<g;e[c+f]=m&255,f+=p,m/=256,g-=8);e[c+f-p]|=128*r}},{}],6:[function(g,k,h){g=k.exports={};g.nextTick=function(){if("undefined"!==typeof window&&window.setImmediate)return function(a){return window.setImmediate(a)};if("undefined"!==typeof window&&window.postMessage&&window.addEventListener){var e=[];window.addEventListener("message",function(a){a.source===window&&"process-tick"===a.data&&(a.stopPropagation(),0<e.length&&e.shift()())},!0);return function(a){e.push(a);window.postMessage("process-tick",
"*")}}return function(a){setTimeout(a,0)}}();g.title="browser";g.browser=!0;g.env={};g.argv=[];g.binding=function(e){throw Error("process.binding is not supported");};g.cwd=function(){return"/"};g.chdir=function(e){throw Error("process.chdir is not supported");}},{}],4:[function(g,k,h){(function(e){e.EventEmitter||(e.EventEmitter=function(){});e=h.EventEmitter=e.EventEmitter;var a="function"===typeof Array.isArray?Array.isArray:function(a){return"[object Array]"===Object.prototype.toString.call(a)};
e.prototype.setMaxListeners=function(a){this._events||(this._events={});this._events.maxListeners=a};e.prototype.emit=function(c){if("error"===c&&(!this._events||!this._events.error||a(this._events.error)&&!this._events.error.length)){if(arguments[1]instanceof Error)throw arguments[1];throw Error("Uncaught, unspecified 'error' event.");}if(!this._events)return!1;var e=this._events[c];if(!e)return!1;if("function"==typeof e){switch(arguments.length){case 1:e.call(this);break;case 2:e.call(this,arguments[1]);
break;case 3:e.call(this,arguments[1],arguments[2]);break;default:var d=Array.prototype.slice.call(arguments,1);e.apply(this,d)}return!0}if(a(e)){for(var d=Array.prototype.slice.call(arguments,1),e=e.slice(),f=0,b=e.length;f<b;f++)e[f].apply(this,d);return!0}return!1};e.prototype.addListener=function(c,e){if("function"!==typeof e)throw Error("addListener only takes instances of Function");this._events||(this._events={});this.emit("newListener",c,e);if(this._events[c])if(a(this._events[c])){if(!this._events[c].warned){var d;
(d=void 0!==this._events.maxListeners?this._events.maxListeners:10)&&(0<d&&this._events[c].length>d)&&(this._events[c].warned=!0,console.error("(node) warning: possible EventEmitter memory leak detected. %d listeners added. Use emitter.setMaxListeners() to increase limit.",this._events[c].length),console.trace())}this._events[c].push(e)}else this._events[c]=[this._events[c],e];else this._events[c]=e;return this};e.prototype.on=e.prototype.addListener;e.prototype.once=function(a,e){var d=this;d.on(a,
function b(){d.removeListener(a,b);e.apply(this,arguments)});return this};e.prototype.removeListener=function(c,e){if("function"!==typeof e)throw Error("removeListener only takes instances of Function");if(!this._events||!this._events[c])return this;var d=this._events[c];if(a(d)){var f;a:if(d.indexOf)f=d.indexOf(e);else{for(f=0;f<d.length;f++)if(e===d[f])break a;f=-1}if(0>f)return this;d.splice(f,1);0==d.length&&delete this._events[c]}else this._events[c]===e&&delete this._events[c];return this};
e.prototype.removeAllListeners=function(a){if(0===arguments.length)return this._events={},this;a&&(this._events&&this._events[a])&&(this._events[a]=null);return this};e.prototype.listeners=function(c){this._events||(this._events={});this._events[c]||(this._events[c]=[]);a(this._events[c])||(this._events[c]=[this._events[c]]);return this._events[c]}})(g("__browserify_process"))},{__browserify_process:6}],"buffer-browserify":[function(g,k,h){k.exports=g("q9TxCC")},{}],q9TxCC:[function(g,k,h){function e(a){this.length=
a}function a(a){return 16>a?"0"+a.toString(16):a.toString(16)}function c(a){for(var b=[],x=0;x<a.length;x++)if(127>=a.charCodeAt(x))b.push(a.charCodeAt(x));else for(var c=encodeURIComponent(a.charAt(x)).substr(1).split("%"),d=0;d<c.length;d++)b.push(parseInt(c[d],16));return b}function m(a,b,x,c){for(var d=0;d<c&&!(d+x>=b.length||d>=a.length);)b[d+x]=a[d],d++;return d}function d(a){try{return decodeURIComponent(a)}catch(b){return String.fromCharCode(65533)}}function f(a){a=~~Math.ceil(+a);return 0>
a?0:a}function b(a,C,x){if(!(this instanceof b))return new b(a,C,x);if("number"===typeof x)this.length=f(C),this.parent=a,this.offset=x;else{switch(x=typeof a){case "number":this.length=f(a);break;case "string":this.length=b.byteLength(a,C);break;case "object":this.length=f(a.length);break;default:throw Error("First argument needs to be a number, array or string.");}if(this.length>b.poolSize)this.parent=new e(this.length),this.offset=0;else{if(!A||A.length-A.used<this.length)A=new e(b.poolSize),A.used=
0;this.parent=A;this.offset=A.used;A.used+=this.length}if(Array.isArray(a)||b.isBuffer(a)||a&&"object"===typeof a&&"number"===typeof a.length)for(C=0;C<this.length;C++)this.parent[C+this.offset]=a instanceof b?a.readUInt8(C):a[C];else"string"==x&&(this.length=this.write(a,0,C))}}function q(a,b,x,c){var d=0;c||(l.ok("boolean"===typeof x,"missing or invalid endian"),l.ok(void 0!==b&&null!==b,"missing offset"),l.ok(b+1<a.length,"Trying to read beyond buffer length"));if(b>=a.length)return 0;x?(d=a.parent[a.offset+
b]<<8,b+1<a.length&&(d|=a.parent[a.offset+b+1])):(d=a.parent[a.offset+b],b+1<a.length&&(d|=a.parent[a.offset+b+1]<<8));return d}function w(a,b,x,c){var d=0;c||(l.ok("boolean"===typeof x,"missing or invalid endian"),l.ok(void 0!==b&&null!==b,"missing offset"),l.ok(b+3<a.length,"Trying to read beyond buffer length"));if(b>=a.length)return 0;x?(b+1<a.length&&(d=a.parent[a.offset+b+1]<<16),b+2<a.length&&(d|=a.parent[a.offset+b+2]<<8),b+3<a.length&&(d|=a.parent[a.offset+b+3]),d+=a.parent[a.offset+b]<<
24>>>0):(b+2<a.length&&(d=a.parent[a.offset+b+2]<<16),b+1<a.length&&(d|=a.parent[a.offset+b+1]<<8),d|=a.parent[a.offset+b],b+3<a.length&&(d+=a.parent[a.offset+b+3]<<24>>>0));return d}function p(a,b,x,c){c||(l.ok("boolean"===typeof x,"missing or invalid endian"),l.ok(void 0!==b&&null!==b,"missing offset"),l.ok(b+1<a.length,"Trying to read beyond buffer length"));a=q(a,b,x,c);return a&32768?-1*(65535-a+1):a}function t(a,b,c,d){d||(l.ok("boolean"===typeof c,"missing or invalid endian"),l.ok(void 0!==
b&&null!==b,"missing offset"),l.ok(b+3<a.length,"Trying to read beyond buffer length"));a=w(a,b,c,d);return a&2147483648?-1*(4294967295-a+1):a}function v(a,b,c,d){d||(l.ok("boolean"===typeof c,"missing or invalid endian"),l.ok(b+3<a.length,"Trying to read beyond buffer length"));return g("./buffer_ieee754").readIEEE754(a,b,c,23,4)}function r(a,b,c,d){d||(l.ok("boolean"===typeof c,"missing or invalid endian"),l.ok(b+7<a.length,"Trying to read beyond buffer length"));return g("./buffer_ieee754").readIEEE754(a,
b,c,52,8)}function s(a,b){l.ok("number"==typeof a,"cannot write a non-number as a number");l.ok(0<=a,"specified a negative value for writing an unsigned value");l.ok(a<=b,"value is larger than maximum value for type");l.ok(Math.floor(a)===a,"value has a fractional component")}function u(a,b,c,d,e){e||(l.ok(void 0!==b&&null!==b,"missing value"),l.ok("boolean"===typeof d,"missing or invalid endian"),l.ok(void 0!==c&&null!==c,"missing offset"),l.ok(c+1<a.length,"trying to write beyond buffer length"),
s(b,65535));for(e=0;e<Math.min(a.length-c,2);e++)a.parent[a.offset+c+e]=(b&255<<8*(d?1-e:e))>>>8*(d?1-e:e)}function n(a,b,c,d,e){e||(l.ok(void 0!==b&&null!==b,"missing value"),l.ok("boolean"===typeof d,"missing or invalid endian"),l.ok(void 0!==c&&null!==c,"missing offset"),l.ok(c+3<a.length,"trying to write beyond buffer length"),s(b,4294967295));for(e=0;e<Math.min(a.length-c,4);e++)a.parent[a.offset+c+e]=b>>>8*(d?3-e:e)&255}function E(a,b,c){l.ok("number"==typeof a,"cannot write a non-number as a number");
l.ok(a<=b,"value larger than maximum allowed value");l.ok(a>=c,"value smaller than minimum allowed value");l.ok(Math.floor(a)===a,"value has a fractional component")}function F(a,b,c){l.ok("number"==typeof a,"cannot write a non-number as a number");l.ok(a<=b,"value larger than maximum allowed value");l.ok(a>=c,"value smaller than minimum allowed value")}function G(a,b,c,d,e){e||(l.ok(void 0!==b&&null!==b,"missing value"),l.ok("boolean"===typeof d,"missing or invalid endian"),l.ok(void 0!==c&&null!==
c,"missing offset"),l.ok(c+1<a.length,"Trying to write beyond buffer length"),E(b,32767,-32768));0<=b?u(a,b,c,d,e):u(a,65535+b+1,c,d,e)}function H(a,b,c,d,e){e||(l.ok(void 0!==b&&null!==b,"missing value"),l.ok("boolean"===typeof d,"missing or invalid endian"),l.ok(void 0!==c&&null!==c,"missing offset"),l.ok(c+3<a.length,"Trying to write beyond buffer length"),E(b,2147483647,-2147483648));0<=b?n(a,b,c,d,e):n(a,4294967295+b+1,c,d,e)}function I(a,b,c,d,e){e||(l.ok(void 0!==b&&null!==b,"missing value"),
l.ok("boolean"===typeof d,"missing or invalid endian"),l.ok(void 0!==c&&null!==c,"missing offset"),l.ok(c+3<a.length,"Trying to write beyond buffer length"),F(b,3.4028234663852886E38,-3.4028234663852886E38));g("./buffer_ieee754").writeIEEE754(a,b,c,d,23,4)}function J(a,b,c,d,e){e||(l.ok(void 0!==b&&null!==b,"missing value"),l.ok("boolean"===typeof d,"missing or invalid endian"),l.ok(void 0!==c&&null!==c,"missing offset"),l.ok(c+7<a.length,"Trying to write beyond buffer length"),F(b,1.7976931348623157E308,
-1.7976931348623157E308));g("./buffer_ieee754").writeIEEE754(a,b,c,d,52,8)}var l=g("assert");h.INSPECT_MAX_BYTES=50;e.byteLength=function(a,b){switch(b||"utf8"){case "hex":return a.length/2;case "utf8":case "utf-8":return c(a).length;case "ascii":case "binary":return a.length;case "base64":return g("base64-js").toByteArray(a).length;default:throw Error("Unknown encoding");}};e.prototype.utf8Write=function(a,b,x){return e._charsWritten=m(c(a),this,b,x)};e.prototype.asciiWrite=function(a,b,c){for(var d=
[],f=0;f<a.length;f++)d.push(a.charCodeAt(f)&255);return e._charsWritten=m(d,this,b,c)};e.prototype.binaryWrite=e.prototype.asciiWrite;e.prototype.base64Write=function(a,b,c){return e._charsWritten=m(g("base64-js").toByteArray(a),this,b,c)};e.prototype.base64Slice=function(a,b){var c=Array.prototype.slice.apply(this,arguments);return g("base64-js").fromByteArray(c)};e.prototype.utf8Slice=function(){for(var a=Array.prototype.slice.apply(this,arguments),b="",c="",e=0;e<a.length;)127>=a[e]?(b+=d(c)+
String.fromCharCode(a[e]),c=""):c+="%"+a[e].toString(16),e++;return b+d(c)};e.prototype.asciiSlice=function(){for(var a=Array.prototype.slice.apply(this,arguments),b="",c=0;c<a.length;c++)b+=String.fromCharCode(a[c]);return b};e.prototype.binarySlice=e.prototype.asciiSlice;e.prototype.inspect=function(){for(var b=[],c=this.length,d=0;d<c;d++)if(b[d]=a(this[d]),d==h.INSPECT_MAX_BYTES){b[d+1]="...";break}return"<SlowBuffer "+b.join(" ")+">"};e.prototype.hexSlice=function(b,c){var d=this.length;if(!b||
0>b)b=0;if(!c||0>c||c>d)c=d;for(var d="",e=b;e<c;e++)d+=a(this[e]);return d};e.prototype.toString=function(a,b,c){a=String(a||"utf8").toLowerCase();b=+b||0;"undefined"==typeof c&&(c=this.length);if(+c==b)return"";switch(a){case "hex":return this.hexSlice(b,c);case "utf8":case "utf-8":return this.utf8Slice(b,c);case "ascii":return this.asciiSlice(b,c);case "binary":return this.binarySlice(b,c);case "base64":return this.base64Slice(b,c);case "ucs2":case "ucs-2":return this.ucs2Slice(b,c);default:throw Error("Unknown encoding");
}};e.prototype.hexWrite=function(a,b,c){b=+b||0;var d=this.length-b;c?(c=+c,c>d&&(c=d)):c=d;d=a.length;if(d%2)throw Error("Invalid hex string");c>d/2&&(c=d/2);for(d=0;d<c;d++){var f=parseInt(a.substr(2*d,2),16);if(isNaN(f))throw Error("Invalid hex string");this[b+d]=f}e._charsWritten=2*d;return d};e.prototype.write=function(a,b,c,d){if(isFinite(b))isFinite(c)||(d=c,c=void 0);else{var e=d;d=b;b=c;c=e}b=+b||0;e=this.length-b;c?(c=+c,c>e&&(c=e)):c=e;d=String(d||"utf8").toLowerCase();switch(d){case "hex":return this.hexWrite(a,
b,c);case "utf8":case "utf-8":return this.utf8Write(a,b,c);case "ascii":return this.asciiWrite(a,b,c);case "binary":return this.binaryWrite(a,b,c);case "base64":return this.base64Write(a,b,c);case "ucs2":case "ucs-2":return this.ucs2Write(a,b,c);default:throw Error("Unknown encoding");}};e.prototype.slice=function(a,c){void 0===c&&(c=this.length);if(c>this.length)throw Error("oob");if(a>c)throw Error("oob");return new b(this,c-a,+a)};e.prototype.copy=function(a,b,c,d){for(var e=[];c<d;c++)l.ok("undefined"!==
typeof this[c],"copying undefined buffer bytes!"),e.push(this[c]);for(c=b;c<b+e.length;c++)a[c]=e[c-b]};e.prototype.fill=function(a,b,c){if(c>this.length)throw Error("oob");if(b>c)throw Error("oob");for(;b<c;b++)this[b]=a};h.SlowBuffer=e;h.Buffer=b;b.poolSize=8192;var A;b.isBuffer=function(a){return a instanceof b||a instanceof e};b.concat=function(a,c){if(!Array.isArray(a))throw Error("Usage: Buffer.concat(list, [totalLength])\n       list should be an Array.");if(0===a.length)return new b(0);if(1===
a.length)return a[0];if("number"!==typeof c)for(var d=c=0;d<a.length;d++){var e=a[d];c+=e.length}for(var f=new b(c),g=0,d=0;d<a.length;d++)e=a[d],e.copy(f,g),g+=e.length;return f};b.prototype.inspect=function(){for(var b=[],c=this.length,d=0;d<c;d++)if(b[d]=a(this.parent[d+this.offset]),d==h.INSPECT_MAX_BYTES){b[d+1]="...";break}return"<Buffer "+b.join(" ")+">"};b.prototype.get=function(a){if(0>a||a>=this.length)throw Error("oob");return this.parent[this.offset+a]};b.prototype.set=function(a,b){if(0>
a||a>=this.length)throw Error("oob");return this.parent[this.offset+a]=b};b.prototype.write=function(a,c,d,f){if(isFinite(c))isFinite(d)||(f=d,d=void 0);else{var g=f;f=c;c=d;d=g}c=+c||0;g=this.length-c;d?(d=+d,d>g&&(d=g)):d=g;f=String(f||"utf8").toLowerCase();switch(f){case "hex":a=this.parent.hexWrite(a,this.offset+c,d);break;case "utf8":case "utf-8":a=this.parent.utf8Write(a,this.offset+c,d);break;case "ascii":a=this.parent.asciiWrite(a,this.offset+c,d);break;case "binary":a=this.parent.binaryWrite(a,
this.offset+c,d);break;case "base64":a=this.parent.base64Write(a,this.offset+c,d);break;case "ucs2":case "ucs-2":a=this.parent.ucs2Write(a,this.offset+c,d);break;default:throw Error("Unknown encoding");}b._charsWritten=e._charsWritten;return a};b.prototype.toString=function(a,b,c){a=String(a||"utf8").toLowerCase();"undefined"==typeof b||0>b?b=0:b>this.length&&(b=this.length);"undefined"==typeof c||c>this.length?c=this.length:0>c&&(c=0);b+=this.offset;c+=this.offset;switch(a){case "hex":return this.parent.hexSlice(b,
c);case "utf8":case "utf-8":return this.parent.utf8Slice(b,c);case "ascii":return this.parent.asciiSlice(b,c);case "binary":return this.parent.binarySlice(b,c);case "base64":return this.parent.base64Slice(b,c);case "ucs2":case "ucs-2":return this.parent.ucs2Slice(b,c);default:throw Error("Unknown encoding");}};b.byteLength=e.byteLength;b.prototype.fill=function(a,b,c){a||(a=0);b||(b=0);c||(c=this.length);"string"===typeof a&&(a=a.charCodeAt(0));if("number"!==typeof a||isNaN(a))throw Error("value is not a number");
if(c<b)throw Error("end < start");if(c===b||0==this.length)return 0;if(0>b||b>=this.length)throw Error("start out of bounds");if(0>c||c>this.length)throw Error("end out of bounds");return this.parent.fill(a,b+this.offset,c+this.offset)};b.prototype.copy=function(a,b,c,d){c||(c=0);d||(d=this.length);b||(b=0);if(d<c)throw Error("sourceEnd < sourceStart");if(d===c||0==a.length||0==this.length)return 0;if(0>b||b>=a.length)throw Error("targetStart out of bounds");if(0>c||c>=this.length)throw Error("sourceStart out of bounds");
if(0>d||d>this.length)throw Error("sourceEnd out of bounds");d>this.length&&(d=this.length);a.length-b<d-c&&(d=a.length-b+c);return this.parent.copy(a.parent,b+a.offset,c+this.offset,d+this.offset)};b.prototype.slice=function(a,c){void 0===c&&(c=this.length);if(c>this.length)throw Error("oob");if(a>c)throw Error("oob");return new b(this.parent,c-a,+a+this.offset)};b.prototype.utf8Slice=function(a,b){return this.toString("utf8",a,b)};b.prototype.binarySlice=function(a,b){return this.toString("binary",
a,b)};b.prototype.asciiSlice=function(a,b){return this.toString("ascii",a,b)};b.prototype.utf8Write=function(a,b){return this.write(a,b,"utf8")};b.prototype.binaryWrite=function(a,b){return this.write(a,b,"binary")};b.prototype.asciiWrite=function(a,b){return this.write(a,b,"ascii")};b.prototype.readUInt8=function(a,b){b||(l.ok(void 0!==a&&null!==a,"missing offset"),l.ok(a<this.length,"Trying to read beyond buffer length"));if(!(a>=this.length))return this.parent[this.offset+a]};b.prototype.readUInt16LE=
function(a,b){return q(this,a,!1,b)};b.prototype.readUInt16BE=function(a,b){return q(this,a,!0,b)};b.prototype.readUInt32LE=function(a,b){return w(this,a,!1,b)};b.prototype.readUInt32BE=function(a,b){return w(this,a,!0,b)};b.prototype.readInt8=function(a,b){var c;b||(l.ok(void 0!==a&&null!==a,"missing offset"),l.ok(a<this.length,"Trying to read beyond buffer length"));if(!(a>=this.length))return(c=this.parent[this.offset+a]&128)?-1*(255-this.parent[this.offset+a]+1):this.parent[this.offset+a]};b.prototype.readInt16LE=
function(a,b){return p(this,a,!1,b)};b.prototype.readInt16BE=function(a,b){return p(this,a,!0,b)};b.prototype.readInt32LE=function(a,b){return t(this,a,!1,b)};b.prototype.readInt32BE=function(a,b){return t(this,a,!0,b)};b.prototype.readFloatLE=function(a,b){return v(this,a,!1,b)};b.prototype.readFloatBE=function(a,b){return v(this,a,!0,b)};b.prototype.readDoubleLE=function(a,b){return r(this,a,!1,b)};b.prototype.readDoubleBE=function(a,b){return r(this,a,!0,b)};b.prototype.writeUInt8=function(a,b,
c){c||(l.ok(void 0!==a&&null!==a,"missing value"),l.ok(void 0!==b&&null!==b,"missing offset"),l.ok(b<this.length,"trying to write beyond buffer length"),s(a,255));b<this.length&&(this.parent[this.offset+b]=a)};b.prototype.writeUInt16LE=function(a,b,c){u(this,a,b,!1,c)};b.prototype.writeUInt16BE=function(a,b,c){u(this,a,b,!0,c)};b.prototype.writeUInt32LE=function(a,b,c){n(this,a,b,!1,c)};b.prototype.writeUInt32BE=function(a,b,c){n(this,a,b,!0,c)};b.prototype.writeInt8=function(a,b,c){c||(l.ok(void 0!==
a&&null!==a,"missing value"),l.ok(void 0!==b&&null!==b,"missing offset"),l.ok(b<this.length,"Trying to write beyond buffer length"),E(a,127,-128));0<=a?this.writeUInt8(a,b,c):this.writeUInt8(255+a+1,b,c)};b.prototype.writeInt16LE=function(a,b,c){G(this,a,b,!1,c)};b.prototype.writeInt16BE=function(a,b,c){G(this,a,b,!0,c)};b.prototype.writeInt32LE=function(a,b,c){H(this,a,b,!1,c)};b.prototype.writeInt32BE=function(a,b,c){H(this,a,b,!0,c)};b.prototype.writeFloatLE=function(a,b,c){I(this,a,b,!1,c)};b.prototype.writeFloatBE=
function(a,b,c){I(this,a,b,!0,c)};b.prototype.writeDoubleLE=function(a,b,c){J(this,a,b,!1,c)};b.prototype.writeDoubleBE=function(a,b,c){J(this,a,b,!0,c)};e.prototype.readUInt8=b.prototype.readUInt8;e.prototype.readUInt16LE=b.prototype.readUInt16LE;e.prototype.readUInt16BE=b.prototype.readUInt16BE;e.prototype.readUInt32LE=b.prototype.readUInt32LE;e.prototype.readUInt32BE=b.prototype.readUInt32BE;e.prototype.readInt8=b.prototype.readInt8;e.prototype.readInt16LE=b.prototype.readInt16LE;e.prototype.readInt16BE=
b.prototype.readInt16BE;e.prototype.readInt32LE=b.prototype.readInt32LE;e.prototype.readInt32BE=b.prototype.readInt32BE;e.prototype.readFloatLE=b.prototype.readFloatLE;e.prototype.readFloatBE=b.prototype.readFloatBE;e.prototype.readDoubleLE=b.prototype.readDoubleLE;e.prototype.readDoubleBE=b.prototype.readDoubleBE;e.prototype.writeUInt8=b.prototype.writeUInt8;e.prototype.writeUInt16LE=b.prototype.writeUInt16LE;e.prototype.writeUInt16BE=b.prototype.writeUInt16BE;e.prototype.writeUInt32LE=b.prototype.writeUInt32LE;
e.prototype.writeUInt32BE=b.prototype.writeUInt32BE;e.prototype.writeInt8=b.prototype.writeInt8;e.prototype.writeInt16LE=b.prototype.writeInt16LE;e.prototype.writeInt16BE=b.prototype.writeInt16BE;e.prototype.writeInt32LE=b.prototype.writeInt32LE;e.prototype.writeInt32BE=b.prototype.writeInt32BE;e.prototype.writeFloatLE=b.prototype.writeFloatLE;e.prototype.writeFloatBE=b.prototype.writeFloatBE;e.prototype.writeDoubleLE=b.prototype.writeDoubleLE;e.prototype.writeDoubleBE=b.prototype.writeDoubleBE},
{assert:1,"./buffer_ieee754":5,"base64-js":7}],7:[function(g,k,h){(function(e){k.exports.toByteArray=function(a){var c,e,d,f,b;if(0<a.length%4)throw"Invalid string. Length must be a multiple of 4";f=a.indexOf("=");f=0<f?a.length-f:0;b=[];e=0<f?a.length-4:a.length;for(c=0;c<e;c+=4)d="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".indexOf(a[c])<<18|"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".indexOf(a[c+1])<<12|"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".indexOf(a[c+
2])<<6|"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".indexOf(a[c+3]),b.push((d&16711680)>>16),b.push((d&65280)>>8),b.push(d&255);2===f?(d="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".indexOf(a[c])<<2|"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".indexOf(a[c+1])>>4,b.push(d&255)):1===f&&(d="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".indexOf(a[c])<<10|"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".indexOf(a[c+
1])<<4|"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".indexOf(a[c+2])>>2,b.push(d>>8&255),b.push(d&255));return b};k.exports.fromByteArray=function(a){var c,e=a.length%3,d="",f,b;c=0;for(b=a.length-e;c<b;c+=3)f=(a[c]<<16)+(a[c+1]<<8)+a[c+2],d+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[f>>18&63]+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[f>>12&63]+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[f>>6&63]+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[f&
63];switch(e){case 1:f=a[a.length-1];d+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[f>>2];d+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[f<<4&63];d+="==";break;case 2:f=(a[a.length-2]<<8)+a[a.length-1],d+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[f>>10],d+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[f>>4&63],d+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[f<<2&63],d+="="}return d}})()},
{}],8:[function(g,k,h){h.readIEEE754=function(e,a,c,g,d){var f;f=8*d-g-1;var b=(1<<f)-1,h=b>>1,k=-7;d=c?0:d-1;var p=c?1:-1,t=e[a+d];d+=p;c=t&(1<<-k)-1;t>>=-k;for(k+=f;0<k;c=256*c+e[a+d],d+=p,k-=8);f=c&(1<<-k)-1;c>>=-k;for(k+=g;0<k;f=256*f+e[a+d],d+=p,k-=8);if(0===c)c=1-h;else{if(c===b)return f?NaN:Infinity*(t?-1:1);f+=Math.pow(2,g);c-=h}return(t?-1:1)*f*Math.pow(2,c-g)};h.writeIEEE754=function(e,a,c,g,d,f){var b,h=8*f-d-1,k=(1<<h)-1,p=k>>1,t=23===d?Math.pow(2,-24)-Math.pow(2,-77):0;f=g?f-1:0;var v=
g?-1:1,r=0>a||0===a&&0>1/a?1:0;a=Math.abs(a);isNaN(a)||Infinity===a?(a=isNaN(a)?1:0,g=k):(g=Math.floor(Math.log(a)/Math.LN2),1>a*(b=Math.pow(2,-g))&&(g--,b*=2),a=1<=g+p?a+t/b:a+t*Math.pow(2,1-p),2<=a*b&&(g++,b/=2),g+p>=k?(a=0,g=k):1<=g+p?(a=(a*b-1)*Math.pow(2,d),g+=p):(a=a*Math.pow(2,p-1)*Math.pow(2,d),g=0));for(;8<=d;e[c+f]=a&255,f+=v,a/=256,d-=8);g=g<<d|a;for(h+=d;0<h;e[c+f]=g&255,f+=v,g/=256,h-=8);e[c+f-v]|=128*r}},{}],3:[function(g,k,h){function e(a){this.length=a}function a(a){return 16>a?"0"+
a.toString(16):a.toString(16)}function c(a){for(var b=[],c=0;c<a.length;c++)if(127>=a.charCodeAt(c))b.push(a.charCodeAt(c));else for(var d=encodeURIComponent(a.charAt(c)).substr(1).split("%"),e=0;e<d.length;e++)b.push(parseInt(d[e],16));return b}function m(a,b,c,d){for(var e=0;e<d&&!(e+c>=b.length||e>=a.length);)b[e+c]=a[e],e++;return e}function d(a){try{return decodeURIComponent(a)}catch(b){return String.fromCharCode(65533)}}function f(a){a=~~Math.ceil(+a);return 0>a?0:a}function b(a,c,d){if(!(this instanceof
b))return new b(a,c,d);if("number"===typeof d)this.length=f(c),this.parent=a,this.offset=d;else{switch(d=typeof a){case "number":this.length=f(a);break;case "string":this.length=b.byteLength(a,c);break;case "object":this.length=f(a.length);break;default:throw Error("First argument needs to be a number, array or string.");}if(this.length>b.poolSize)this.parent=new e(this.length),this.offset=0;else{if(!A||A.length-A.used<this.length)A=new e(b.poolSize),A.used=0;this.parent=A;this.offset=A.used;A.used+=
this.length}if(Array.isArray(a)||b.isBuffer(a)||a&&"object"===typeof a&&"number"===typeof a.length)for(c=0;c<this.length;c++)this.parent[c+this.offset]=a[c];else"string"==d&&(this.length=this.write(a,0,c))}}function q(a,b,c,d){var e=0;d||(l.ok("boolean"===typeof c,"missing or invalid endian"),l.ok(void 0!==b&&null!==b,"missing offset"),l.ok(b+1<a.length,"Trying to read beyond buffer length"));c?(e=a.parent[a.offset+b]<<8,e|=a.parent[a.offset+b+1]):(e=a.parent[a.offset+b],e|=a.parent[a.offset+b+1]<<
8);return e}function p(a,b,c,d){var e=0;d||(l.ok("boolean"===typeof c,"missing or invalid endian"),l.ok(void 0!==b&&null!==b,"missing offset"),l.ok(b+3<a.length,"Trying to read beyond buffer length"));c?(e=a.parent[a.offset+b+1]<<16,e|=a.parent[a.offset+b+2]<<8,e|=a.parent[a.offset+b+3],e+=a.parent[a.offset+b]<<24>>>0):(e=a.parent[a.offset+b+2]<<16,e|=a.parent[a.offset+b+1]<<8,e|=a.parent[a.offset+b],e+=a.parent[a.offset+b+3]<<24>>>0);return e}function v(a,b,c,d){d||(l.ok("boolean"===typeof c,"missing or invalid endian"),
l.ok(void 0!==b&&null!==b,"missing offset"),l.ok(b+1<a.length,"Trying to read beyond buffer length"));a=q(a,b,c,d);return a&32768?-1*(65535-a+1):a}function t(a,b,c,d){d||(l.ok("boolean"===typeof c,"missing or invalid endian"),l.ok(void 0!==b&&null!==b,"missing offset"),l.ok(b+3<a.length,"Trying to read beyond buffer length"));a=p(a,b,c,d);return a&2147483648?-1*(4294967295-a+1):a}function y(a,b,c,d){d||(l.ok("boolean"===typeof c,"missing or invalid endian"),l.ok(b+3<a.length,"Trying to read beyond buffer length"));
return g("./buffer_ieee754").readIEEE754(a,b,c,23,4)}function r(a,b,c,d){d||(l.ok("boolean"===typeof c,"missing or invalid endian"),l.ok(b+7<a.length,"Trying to read beyond buffer length"));return g("./buffer_ieee754").readIEEE754(a,b,c,52,8)}function s(a,b){l.ok("number"==typeof a,"cannot write a non-number as a number");l.ok(0<=a,"specified a negative value for writing an unsigned value");l.ok(a<=b,"value is larger than maximum value for type");l.ok(Math.floor(a)===a,"value has a fractional component")}
function u(a,b,c,d,e){e||(l.ok(void 0!==b&&null!==b,"missing value"),l.ok("boolean"===typeof d,"missing or invalid endian"),l.ok(void 0!==c&&null!==c,"missing offset"),l.ok(c+1<a.length,"trying to write beyond buffer length"),s(b,65535));d?(a.parent[a.offset+c]=(b&65280)>>>8,a.parent[a.offset+c+1]=b&255):(a.parent[a.offset+c+1]=(b&65280)>>>8,a.parent[a.offset+c]=b&255)}function n(a,b,c,d,e){e||(l.ok(void 0!==b&&null!==b,"missing value"),l.ok("boolean"===typeof d,"missing or invalid endian"),l.ok(void 0!==
c&&null!==c,"missing offset"),l.ok(c+3<a.length,"trying to write beyond buffer length"),s(b,4294967295));d?(a.parent[a.offset+c]=b>>>24&255,a.parent[a.offset+c+1]=b>>>16&255,a.parent[a.offset+c+2]=b>>>8&255,a.parent[a.offset+c+3]=b&255):(a.parent[a.offset+c+3]=b>>>24&255,a.parent[a.offset+c+2]=b>>>16&255,a.parent[a.offset+c+1]=b>>>8&255,a.parent[a.offset+c]=b&255)}function E(a,b,c){l.ok("number"==typeof a,"cannot write a non-number as a number");l.ok(a<=b,"value larger than maximum allowed value");
l.ok(a>=c,"value smaller than minimum allowed value");l.ok(Math.floor(a)===a,"value has a fractional component")}function F(a,b,c){l.ok("number"==typeof a,"cannot write a non-number as a number");l.ok(a<=b,"value larger than maximum allowed value");l.ok(a>=c,"value smaller than minimum allowed value")}function G(a,b,c,d,e){e||(l.ok(void 0!==b&&null!==b,"missing value"),l.ok("boolean"===typeof d,"missing or invalid endian"),l.ok(void 0!==c&&null!==c,"missing offset"),l.ok(c+1<a.length,"Trying to write beyond buffer length"),
E(b,32767,-32768));0<=b?u(a,b,c,d,e):u(a,65535+b+1,c,d,e)}function H(a,b,c,d,e){e||(l.ok(void 0!==b&&null!==b,"missing value"),l.ok("boolean"===typeof d,"missing or invalid endian"),l.ok(void 0!==c&&null!==c,"missing offset"),l.ok(c+3<a.length,"Trying to write beyond buffer length"),E(b,2147483647,-2147483648));0<=b?n(a,b,c,d,e):n(a,4294967295+b+1,c,d,e)}function I(a,b,c,d,e){e||(l.ok(void 0!==b&&null!==b,"missing value"),l.ok("boolean"===typeof d,"missing or invalid endian"),l.ok(void 0!==c&&null!==
c,"missing offset"),l.ok(c+3<a.length,"Trying to write beyond buffer length"),F(b,3.4028234663852886E38,-3.4028234663852886E38));g("./buffer_ieee754").writeIEEE754(a,b,c,d,23,4)}function J(a,b,c,d,e){e||(l.ok(void 0!==b&&null!==b,"missing value"),l.ok("boolean"===typeof d,"missing or invalid endian"),l.ok(void 0!==c&&null!==c,"missing offset"),l.ok(c+7<a.length,"Trying to write beyond buffer length"),F(b,1.7976931348623157E308,-1.7976931348623157E308));g("./buffer_ieee754").writeIEEE754(a,b,c,d,52,
8)}var l=g("assert");h.INSPECT_MAX_BYTES=50;e.byteLength=function(a,b){switch(b||"utf8"){case "hex":return a.length/2;case "utf8":case "utf-8":return c(a).length;case "ascii":return a.length;case "base64":return g("base64-js").toByteArray(a).length;default:throw Error("Unknown encoding");}};e.prototype.utf8Write=function(a,b,d){return e._charsWritten=m(c(a),this,b,d)};e.prototype.asciiWrite=function(a,b,c){for(var d=[],f=0;f<a.length;f++)d.push(a.charCodeAt(f)&255);return e._charsWritten=m(d,this,
b,c)};e.prototype.base64Write=function(a,b,c){return e._charsWritten=m(g("base64-js").toByteArray(a),this,b,c)};e.prototype.base64Slice=function(a,b){var c=Array.prototype.slice.apply(this,arguments);return g("base64-js").fromByteArray(c)};e.prototype.utf8Slice=function(){for(var a=Array.prototype.slice.apply(this,arguments),b="",c="",e=0;e<a.length;)127>=a[e]?(b+=d(c)+String.fromCharCode(a[e]),c=""):c+="%"+a[e].toString(16),e++;return b+d(c)};e.prototype.asciiSlice=function(){for(var a=Array.prototype.slice.apply(this,
arguments),b="",c=0;c<a.length;c++)b+=String.fromCharCode(a[c]);return b};e.prototype.inspect=function(){for(var b=[],c=this.length,d=0;d<c;d++)if(b[d]=a(this[d]),d==h.INSPECT_MAX_BYTES){b[d+1]="...";break}return"<SlowBuffer "+b.join(" ")+">"};e.prototype.hexSlice=function(b,c){var d=this.length;if(!b||0>b)b=0;if(!c||0>c||c>d)c=d;for(var d="",e=b;e<c;e++)d+=a(this[e]);return d};e.prototype.toString=function(a,b,c){a=String(a||"utf8").toLowerCase();b=+b||0;"undefined"==typeof c&&(c=this.length);if(+c==
b)return"";switch(a){case "hex":return this.hexSlice(b,c);case "utf8":case "utf-8":return this.utf8Slice(b,c);case "ascii":return this.asciiSlice(b,c);case "binary":return this.binarySlice(b,c);case "base64":return this.base64Slice(b,c);case "ucs2":case "ucs-2":return this.ucs2Slice(b,c);default:throw Error("Unknown encoding");}};e.prototype.hexWrite=function(a,b,c){b=+b||0;var d=this.length-b;c?(c=+c,c>d&&(c=d)):c=d;d=a.length;if(d%2)throw Error("Invalid hex string");c>d/2&&(c=d/2);for(d=0;d<c;d++){var f=
parseInt(a.substr(2*d,2),16);if(isNaN(f))throw Error("Invalid hex string");this[b+d]=f}e._charsWritten=2*d;return d};e.prototype.write=function(a,b,c,d){if(isFinite(b))isFinite(c)||(d=c,c=void 0);else{var e=d;d=b;b=c;c=e}b=+b||0;e=this.length-b;c?(c=+c,c>e&&(c=e)):c=e;d=String(d||"utf8").toLowerCase();switch(d){case "hex":return this.hexWrite(a,b,c);case "utf8":case "utf-8":return this.utf8Write(a,b,c);case "ascii":return this.asciiWrite(a,b,c);case "binary":return this.binaryWrite(a,b,c);case "base64":return this.base64Write(a,
b,c);case "ucs2":case "ucs-2":return this.ucs2Write(a,b,c);default:throw Error("Unknown encoding");}};e.prototype.slice=function(a,c){void 0===c&&(c=this.length);if(c>this.length)throw Error("oob");if(a>c)throw Error("oob");return new b(this,c-a,+a)};e.prototype.copy=function(a,b,c,d){for(var e=[];c<d;c++)l.ok("undefined"!==typeof this[c],"copying undefined buffer bytes!"),e.push(this[c]);for(c=b;c<b+e.length;c++)a[c]=e[c-b]};h.SlowBuffer=e;h.Buffer=b;b.poolSize=8192;var A;b.isBuffer=function(a){return a instanceof
b||a instanceof e};b.concat=function(a,c){if(!Array.isArray(a))throw Error("Usage: Buffer.concat(list, [totalLength])\n       list should be an Array.");if(0===a.length)return new b(0);if(1===a.length)return a[0];if("number"!==typeof c)for(var d=c=0;d<a.length;d++){var e=a[d];c+=e.length}for(var f=new b(c),g=0,d=0;d<a.length;d++)e=a[d],e.copy(f,g),g+=e.length;return f};b.prototype.inspect=function(){for(var b=[],c=this.length,d=0;d<c;d++)if(b[d]=a(this.parent[d+this.offset]),d==h.INSPECT_MAX_BYTES){b[d+
1]="...";break}return"<Buffer "+b.join(" ")+">"};b.prototype.get=function(a){if(0>a||a>=this.length)throw Error("oob");return this.parent[this.offset+a]};b.prototype.set=function(a,b){if(0>a||a>=this.length)throw Error("oob");return this.parent[this.offset+a]=b};b.prototype.write=function(a,c,d,f){if(isFinite(c))isFinite(d)||(f=d,d=void 0);else{var g=f;f=c;c=d;d=g}c=+c||0;g=this.length-c;d?(d=+d,d>g&&(d=g)):d=g;f=String(f||"utf8").toLowerCase();switch(f){case "hex":a=this.parent.hexWrite(a,this.offset+
c,d);break;case "utf8":case "utf-8":a=this.parent.utf8Write(a,this.offset+c,d);break;case "ascii":a=this.parent.asciiWrite(a,this.offset+c,d);break;case "binary":a=this.parent.binaryWrite(a,this.offset+c,d);break;case "base64":a=this.parent.base64Write(a,this.offset+c,d);break;case "ucs2":case "ucs-2":a=this.parent.ucs2Write(a,this.offset+c,d);break;default:throw Error("Unknown encoding");}b._charsWritten=e._charsWritten;return a};b.prototype.toString=function(a,b,c){a=String(a||"utf8").toLowerCase();
"undefined"==typeof b||0>b?b=0:b>this.length&&(b=this.length);"undefined"==typeof c||c>this.length?c=this.length:0>c&&(c=0);b+=this.offset;c+=this.offset;switch(a){case "hex":return this.parent.hexSlice(b,c);case "utf8":case "utf-8":return this.parent.utf8Slice(b,c);case "ascii":return this.parent.asciiSlice(b,c);case "binary":return this.parent.binarySlice(b,c);case "base64":return this.parent.base64Slice(b,c);case "ucs2":case "ucs-2":return this.parent.ucs2Slice(b,c);default:throw Error("Unknown encoding");
}};b.byteLength=e.byteLength;b.prototype.fill=function(a,b,c){a||(a=0);b||(b=0);c||(c=this.length);"string"===typeof a&&(a=a.charCodeAt(0));if("number"!==typeof a||isNaN(a))throw Error("value is not a number");if(c<b)throw Error("end < start");if(c===b||0==this.length)return 0;if(0>b||b>=this.length)throw Error("start out of bounds");if(0>c||c>this.length)throw Error("end out of bounds");return this.parent.fill(a,b+this.offset,c+this.offset)};b.prototype.copy=function(a,b,c,d){c||(c=0);d||(d=this.length);
b||(b=0);if(d<c)throw Error("sourceEnd < sourceStart");if(d===c||0==a.length||0==this.length)return 0;if(0>b||b>=a.length)throw Error("targetStart out of bounds");if(0>c||c>=this.length)throw Error("sourceStart out of bounds");if(0>d||d>this.length)throw Error("sourceEnd out of bounds");d>this.length&&(d=this.length);a.length-b<d-c&&(d=a.length-b+c);return this.parent.copy(a.parent,b+a.offset,c+this.offset,d+this.offset)};b.prototype.slice=function(a,c){void 0===c&&(c=this.length);if(c>this.length)throw Error("oob");
if(a>c)throw Error("oob");return new b(this.parent,c-a,+a+this.offset)};b.prototype.utf8Slice=function(a,b){return this.toString("utf8",a,b)};b.prototype.binarySlice=function(a,b){return this.toString("binary",a,b)};b.prototype.asciiSlice=function(a,b){return this.toString("ascii",a,b)};b.prototype.utf8Write=function(a,b){return this.write(a,b,"utf8")};b.prototype.binaryWrite=function(a,b){return this.write(a,b,"binary")};b.prototype.asciiWrite=function(a,b){return this.write(a,b,"ascii")};b.prototype.readUInt8=
function(a,b){b||(l.ok(void 0!==a&&null!==a,"missing offset"),l.ok(a<this.length,"Trying to read beyond buffer length"));return this.parent[this.offset+a]};b.prototype.readUInt16LE=function(a,b){return q(this,a,!1,b)};b.prototype.readUInt16BE=function(a,b){return q(this,a,!0,b)};b.prototype.readUInt32LE=function(a,b){return p(this,a,!1,b)};b.prototype.readUInt32BE=function(a,b){return p(this,a,!0,b)};b.prototype.readInt8=function(a,b){b||(l.ok(void 0!==a&&null!==a,"missing offset"),l.ok(a<this.length,
"Trying to read beyond buffer length"));return this.parent[this.offset+a]&128?-1*(255-this.parent[this.offset+a]+1):this.parent[this.offset+a]};b.prototype.readInt16LE=function(a,b){return v(this,a,!1,b)};b.prototype.readInt16BE=function(a,b){return v(this,a,!0,b)};b.prototype.readInt32LE=function(a,b){return t(this,a,!1,b)};b.prototype.readInt32BE=function(a,b){return t(this,a,!0,b)};b.prototype.readFloatLE=function(a,b){return y(this,a,!1,b)};b.prototype.readFloatBE=function(a,b){return y(this,
a,!0,b)};b.prototype.readDoubleLE=function(a,b){return r(this,a,!1,b)};b.prototype.readDoubleBE=function(a,b){return r(this,a,!0,b)};b.prototype.writeUInt8=function(a,b,c){c||(l.ok(void 0!==a&&null!==a,"missing value"),l.ok(void 0!==b&&null!==b,"missing offset"),l.ok(b<this.length,"trying to write beyond buffer length"),s(a,255));this.parent[this.offset+b]=a};b.prototype.writeUInt16LE=function(a,b,c){u(this,a,b,!1,c)};b.prototype.writeUInt16BE=function(a,b,c){u(this,a,b,!0,c)};b.prototype.writeUInt32LE=
function(a,b,c){n(this,a,b,!1,c)};b.prototype.writeUInt32BE=function(a,b,c){n(this,a,b,!0,c)};b.prototype.writeInt8=function(a,b,c){c||(l.ok(void 0!==a&&null!==a,"missing value"),l.ok(void 0!==b&&null!==b,"missing offset"),l.ok(b<this.length,"Trying to write beyond buffer length"),E(a,127,-128));0<=a?this.writeUInt8(a,b,c):this.writeUInt8(255+a+1,b,c)};b.prototype.writeInt16LE=function(a,b,c){G(this,a,b,!1,c)};b.prototype.writeInt16BE=function(a,b,c){G(this,a,b,!0,c)};b.prototype.writeInt32LE=function(a,
b,c){H(this,a,b,!1,c)};b.prototype.writeInt32BE=function(a,b,c){H(this,a,b,!0,c)};b.prototype.writeFloatLE=function(a,b,c){I(this,a,b,!1,c)};b.prototype.writeFloatBE=function(a,b,c){I(this,a,b,!0,c)};b.prototype.writeDoubleLE=function(a,b,c){J(this,a,b,!1,c)};b.prototype.writeDoubleBE=function(a,b,c){J(this,a,b,!0,c)};e.prototype.readUInt8=b.prototype.readUInt8;e.prototype.readUInt16LE=b.prototype.readUInt16LE;e.prototype.readUInt16BE=b.prototype.readUInt16BE;e.prototype.readUInt32LE=b.prototype.readUInt32LE;
e.prototype.readUInt32BE=b.prototype.readUInt32BE;e.prototype.readInt8=b.prototype.readInt8;e.prototype.readInt16LE=b.prototype.readInt16LE;e.prototype.readInt16BE=b.prototype.readInt16BE;e.prototype.readInt32LE=b.prototype.readInt32LE;e.prototype.readInt32BE=b.prototype.readInt32BE;e.prototype.readFloatLE=b.prototype.readFloatLE;e.prototype.readFloatBE=b.prototype.readFloatBE;e.prototype.readDoubleLE=b.prototype.readDoubleLE;e.prototype.readDoubleBE=b.prototype.readDoubleBE;e.prototype.writeUInt8=
b.prototype.writeUInt8;e.prototype.writeUInt16LE=b.prototype.writeUInt16LE;e.prototype.writeUInt16BE=b.prototype.writeUInt16BE;e.prototype.writeUInt32LE=b.prototype.writeUInt32LE;e.prototype.writeUInt32BE=b.prototype.writeUInt32BE;e.prototype.writeInt8=b.prototype.writeInt8;e.prototype.writeInt16LE=b.prototype.writeInt16LE;e.prototype.writeInt16BE=b.prototype.writeInt16BE;e.prototype.writeInt32LE=b.prototype.writeInt32LE;e.prototype.writeInt32BE=b.prototype.writeInt32BE;e.prototype.writeFloatLE=b.prototype.writeFloatLE;
e.prototype.writeFloatBE=b.prototype.writeFloatBE;e.prototype.writeDoubleLE=b.prototype.writeDoubleLE;e.prototype.writeDoubleBE=b.prototype.writeDoubleBE},{assert:1,"./buffer_ieee754":8,"base64-js":9}],9:[function(g,k,h){(function(e){k.exports.toByteArray=function(a){var c,e,d,f,b;if(0<a.length%4)throw"Invalid string. Length must be a multiple of 4";f=a.indexOf("=");f=0<f?a.length-f:0;b=[];e=0<f?a.length-4:a.length;for(c=0;c<e;c+=4)d="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".indexOf(a[c])<<
18|"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".indexOf(a[c+1])<<12|"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".indexOf(a[c+2])<<6|"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".indexOf(a[c+3]),b.push((d&16711680)>>16),b.push((d&65280)>>8),b.push(d&255);2===f?(d="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".indexOf(a[c])<<2|"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".indexOf(a[c+1])>>4,b.push(d&
255)):1===f&&(d="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".indexOf(a[c])<<10|"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".indexOf(a[c+1])<<4|"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".indexOf(a[c+2])>>2,b.push(d>>8&255),b.push(d&255));return b};k.exports.fromByteArray=function(a){var c,e=a.length%3,d="",f,b;c=0;for(b=a.length-e;c<b;c+=3)f=(a[c]<<16)+(a[c+1]<<8)+a[c+2],d+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[f>>
18&63]+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[f>>12&63]+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[f>>6&63]+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[f&63];switch(e){case 1:f=a[a.length-1];d+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[f>>2];d+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[f<<4&63];d+="==";break;case 2:f=(a[a.length-2]<<8)+a[a.length-1],d+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[f>>
10],d+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[f>>4&63],d+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[f<<2&63],d+="="}return d}})()},{}]},{},[]);v.exports=k("buffer-browserify")},{}],16:[function(k,v,p){k=v.exports={};k.nextTick=function(){if("undefined"!==typeof window&&window.setImmediate)return function(g){return window.setImmediate(g)};if("undefined"!==typeof window&&window.postMessage&&window.addEventListener){var g=[];window.addEventListener("message",
function(k){k.source===window&&"process-tick"===k.data&&(k.stopPropagation(),0<g.length&&g.shift()())},!0);return function(k){g.push(k);window.postMessage("process-tick","*")}}return function(g){setTimeout(g,0)}}();k.title="browser";k.browser=!0;k.env={};k.argv=[];k.binding=function(g){throw Error("process.binding is not supported");};k.cwd=function(){return"/"};k.chdir=function(g){throw Error("process.chdir is not supported");}},{}]},{},[1]);
